linkPrefix = ""
name = "request-network-smart-contracts"
license = "MIT"
version = "0.2.2"
description = "Smart contracts that implement the Request Network protocol."
homepage = "https://github.com/RequestNetwork/requestNetwork/tree/master/packages/requestNetworkSmartContracts"
buildTime = 2018-05-17T09:58:39.734Z
target = "../docs-smart-contracts"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"
out = "docs"

[interaction]