version: 2

references:
  working_directory: &working_directory ~/repo
  attach_workspace: &attach_workspace
  node_image: &node_image
    image: circleci/node:10
  ipfs_image: &ipfs_image
    image: ipfs/go-ipfs
  ganache_image: &ganache_image
    image: trufflesuite/ganache-cli:v6.1.3
    command:
      - '-l'
      - '90000000'
      - '-m'
      - 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'

jobs:
  build:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - checkout
      - run:
          name: 'Yarn install'
          command: 'yarn install'
      - persist_to_workspace:
          root: *working_directory
          paths: .
  lint-package-json:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'lint package.json files'
          command: 'yarn run packageJsonLint'
  test-request-client.js:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build request-client.js'
          command: 'yarn workspace @requestnetwork/request-client.js run build:commonjs'
      - run:
          name: 'Lint request-client.js'
          command: 'yarn workspace @requestnetwork/request-client.js run lint '
      - run:
          name: 'Test request-client.js'
          command: 'yarn workspace @requestnetwork/request-client.js run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/request-client.js/.nyc_output
  test-data-access:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build data-access'
          command: 'yarn workspace @requestnetwork/data-access run build'
      - run:
          name: 'Lint data-access'
          command: 'yarn workspace @requestnetwork/data-access run lint '
      - run:
          name: 'Test data-access'
          command: 'yarn workspace @requestnetwork/data-access run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/data-access/.nyc_output
  test-transaction-manager:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build transaction-manager'
          command: 'yarn workspace @requestnetwork/transaction-manager run build'
      - run:
          name: 'Lint transaction-manager'
          command: 'yarn workspace @requestnetwork/transaction-manager run lint'
      - run:
          name: 'Test transaction-manager'
          command: 'yarn workspace @requestnetwork/transaction-manager run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/transaction-manager/.nyc_output
  test-ethereum-storage:
    docker:
      - *node_image
      - *ipfs_image
      - *ganache_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run build:lib'
      - run:
          name: 'Lint ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run lint:lib'
      - run:
          name: 'Deploy contracs ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run deploy'
      - run:
          name: 'Test ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run test:lib'
      - run:
          name: 'Build smart contracts ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run build:sol'
      - run:
          name: 'Lint smart contracts ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run lint:sol'
      - run:
          name: 'Test smart contracts ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run test:sol'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/ethereum-storage/.nyc_output
  test-request-logic:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build request-logic'
          command: 'yarn workspace @requestnetwork/request-logic run build'
      - run:
          name: 'Lint request-logic'
          command: 'yarn workspace @requestnetwork/request-logic run lint'
      - run:
          name: 'Test request-logic'
          command: 'yarn workspace @requestnetwork/request-logic run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/request-logic/.nyc_output
  test-advanced-logic:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build advanced-logic'
          command: 'yarn workspace @requestnetwork/advanced-logic run build'
      - run:
          name: 'Lint advanced-logic'
          command: 'yarn workspace @requestnetwork/advanced-logic run lint'
      - run:
          name: 'Test advanced-logic'
          command: 'yarn workspace @requestnetwork/advanced-logic run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/advanced-logic/.nyc_output
  test-request-node:
    docker:
      - *node_image
      - *ipfs_image
      - *ganache_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build request-node'
          command: 'yarn workspace @requestnetwork/request-node run build'
      - run:
          name: 'Lint request-node'
          command: 'yarn workspace @requestnetwork/request-node run lint'
      - run:
          name: 'Deploy test contract from ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run deploy'
      - run:
          name: 'Test request-node'
          command: 'yarn workspace @requestnetwork/request-node run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/request-node/.nyc_output
  test-types:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build types'
          command: 'yarn workspace @requestnetwork/types run build'
      - run:
          name: 'Lint types'
          command: 'yarn workspace @requestnetwork/types run lint'
  test-utils:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build utils'
          command: 'yarn workspace @requestnetwork/utils run build'
      - run:
          name: 'Lint utils'
          command: 'yarn workspace @requestnetwork/utils run lint'
      - run:
          name: 'Test utils'
          command: 'yarn workspace @requestnetwork/utils run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/utils/.nyc_output
  test-epk-signature:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build epk-signature'
          command: 'yarn workspace @requestnetwork/epk-signature run build'
      - run:
          name: 'Lint epk-signature'
          command: 'yarn workspace @requestnetwork/epk-signature run lint'
      - run:
          name: 'Test epk-signature'
          command: 'yarn workspace @requestnetwork/epk-signature run test'
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/epk-signature/.nyc_output
  test-integration-test:
    docker:
      - *node_image
      - *ipfs_image
      - *ganache_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Build integration-test'
          command: 'yarn workspace @requestnetwork/integration-test run build'
      - run:
          name: 'Lint integration-test'
          command: 'yarn workspace @requestnetwork/integration-test run lint'
      - run:
          name: 'Deploy test contract from ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run deploy'
      - run:
          name: 'Start request-node'
          command: 'yarn workspace @requestnetwork/request-node run start'
          background: true
      - run: sleep 3
      - run:
          name: 'Test integration-test'
          command: 'yarn workspace @requestnetwork/integration-test run test'
  publish-coverage:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: *working_directory
      - run:
          name: 'Coverage data-access'
          command: 'yarn workspace @requestnetwork/data-access run coverage'
      - run:
          name: 'Coverage ethereum-storage'
          command: 'yarn workspace @requestnetwork/ethereum-storage run coverage'
      - run:
          name: 'Coverage request-logic'
          command: 'yarn workspace @requestnetwork/request-logic run coverage'
      - run:
          name: 'Coverage advanced-logic'
          command: 'yarn workspace @requestnetwork/advanced-logic run coverage'
      - run:
          name: 'Coverage epk-signature'
          command: 'yarn workspace @requestnetwork/epk-signature run coverage'
      - run:
          name: 'Coverage request-node'
          command: 'yarn workspace @requestnetwork/request-node run coverage'
      - run:
          name: 'Coverage utils'
          command: 'yarn workspace @requestnetwork/utils run coverage'
      - run:
          name: 'Publish Coverage'
          command: 'yarn publish-coverage'
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint-package-json:
          requires:
            - build
      # Test
      - test-request-client.js:
          requires:
            - build
      - test-transaction-manager:
          requires:
            - build
      - test-data-access:
          requires:
            - build
      - test-ethereum-storage:
          requires:
            - build
      - test-request-logic:
          requires:
            - build
      - test-advanced-logic:
          requires:
            - build
      - test-request-node:
          requires:
            - build
      - test-types:
          requires:
            - build
      - test-utils:
          requires:
            - build
      - test-epk-signature:
          requires:
            - build
      - test-integration-test:
          requires:
            - build
      # Publish the code coverage
      - publish-coverage:
          requires:
            - test-request-client.js
            - test-data-access
            - test-transaction-manager
            - test-ethereum-storage
            - test-request-logic
            - test-advanced-logic
            - test-epk-signature
            - test-request-node
            - test-utils
